### PR TITLE
fixed commit revert

### PR DESCRIPTION
**Pull request by tobischw**

### CODE REVIEW

**Comment by dannye** [comment]
If something in those two commits was undesired, I can do it over correctly.
But those two commits had good fixes.

**Comment by tobischw** [comment]
I accidentally had an older version of JPG Raster and committed those files (at least I believe so) while trying to generate the stage catalog, which was causing issues on the build server. I believe we fixed this, unless I'm wrong and I was on the right version. Let me know which one is the case.

**Comment by dannye** [comment]
I'm not actually sure what you mean by that.

All this pull request does is revert these two commits:
https://github.com/oci-pronghorn/JPG-Raster/commit/e30ef27bb35d7cde7deed007587553de7c918242
https://github.com/oci-pronghorn/JPG-Raster/commit/a721292ae58d27dbae067716a5dddc9c836e3aa5

To fix this, these two commits should be taken off the top of master:
https://github.com/oci-pronghorn/JPG-Raster/commit/dae0bd93dbf030b6ac7b98d1fbde65a2eeaddb20
https://github.com/oci-pronghorn/JPG-Raster/commit/ca1ae152311ab0fe00a52517b084cfe8f6b3ad92

**Comment by tobischw** [comment]
You are right, I'll let Preveen know.

**Pull request merged**
